### ISSUE TITLE
Remove `@todo`s code

### ISSUE THREAD

**Issue by matthiasbeyer** [waysome/waysome#467]
This Issue is to track progress of the removals of the `@todo` s in all files.
I will not open an issue for each file, which would be overkill (given the list
of files which contain `@todo`s).

We have 129 `@todo`s in the following files:
- [x] `src/action/manager.c`
- [ ] `src/compositor/buffer/buffer.c`
- [x] `src/compositor/buffer/egl.c`
- [X] `src/compositor/buffer/image.c`
- [ ] `src/compositor/cursor.c`
- [ ] `src/compositor/keyboard.c`
- [ ] `src/compositor/module.c`
- [ ] `src/compositor/monitor.c`
- [X] `src/compositor/wayland/client.c`
- [ ] `src/compositor/wayland/compositor.c`
- [ ] `src/compositor/wayland/keyboard.c`
- [ ] `src/compositor/wayland/pointer.c`
- [ ] `src/compositor/wayland/region.c`
- [ ] `src/compositor/wayland/seat.c`
- [ ] `src/compositor/wayland/seat.h`
- [ ] `src/compositor/wayland/shell_surface.c`
- [ ] `src/compositor/wayland/surface.c`
- [ ] `src/compositor/wayland/xdg_shell.c`
- [ ] `src/compositor/wayland/xdg_surface.c`
- [x] `src/connection/processor.c`
- [ ] `src/input/input_device.c`
- [X] `src/main.c`
- [x] `src/objects/object.c`
- [x] `src/objects/object.h`
- [ ] `src/objects/string.c`
- [X] `src/serialize/json/deserializer.c`
- [ ] `src/serialize/json/deserializer_callbacks.c`
- [x] `src/serialize/json/serializer.c`
- [ ] `src/serialize/json/serializer_state.c`
- [x] `src/values/union.c`
- [x] `src/values/value_type.c`

(Based on commit a243086cd1437dd677820aa88f641a3ab36a193a).

---

To retreive a list files where `@todo`s are located:

``` bash
ack "@todo" -l src/
```

To retreive the number of `@todo`s in the code:

``` bash
ack "@todo" src | wc -l
```

---

Edit: Added `main.c` and sorted list alphabetically.

**Comment by manuelmessner** [comment]
src/main.c is missing right now

**Comment by matthiasbeyer** [comment]
The upper PRs are all I can do, I would like to re-assign this issue to @TheNeikos as soon as these are merged, as most of the `@todo`s are in the compositor code and I don't have a clue what to do there (most of them are just "implement this" ones, ... so ... well, ... it's obious what to do there...)

**Comment by neithernut** [comment]
Nopte that a _lot_ of TODOs are actually refering to features which _may_ be introduced but which have a _fairly_ low priority and/or carry a lot of complexity or are associated with a feature which will not be introduced in _near_ future. This hold true specifically for much of the TODOs in the compositor.

Hence, this meta-issue is nice to track stuff, but the effective priority is to be neclected. I suggest busting this issue in favor for more specific issues, which are targeted at specific subsystems. It was acutally a _ridiculously_ bad idea to start this this way, from a ressource management point of view.

**Comment by matthiasbeyer** [comment]
Well, maybe I stated not clearly enough: The intend of this is _not_ to fix all `@todo` annotation, but to review all of them as some may be outdated or could be implemented with just a few lines of code.

The idea of this is clearly _not_ to do all the stuff which should be done via issue tracking etc!

**Comment by neithernut** [comment]
I'm fine with _that_. However, you should have to stated this more clearly and you should _not_ have assigned this a high priority.

**Comment by matthiasbeyer** [comment]
This was wrong, I agree.
